---
- name: Deploy LEMP stack with Joomla
  hosts: webservers
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - nginx
    - php
    - mysql
    - initapps
    - joomla
