---
- name: Add PHP repository
  ansible.builtin.apt_repository:
    repo: "ppa:ondrej/php"
    state: present

- name: Install PHP and extensions
  ansible.builtin.apt:
    name:
      - "php{{ php_version }}"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-zip"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-intl"
    state: present
    update_cache: true

- name: Ensure PHP-FPM is running and enabled
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: started
    enabled: true
